CREATE TABLE `user_tbl` (
	`user_id` VARCHAR(50) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	`permission` INT(11) NULL DEFAULT NULL,
	`name` VARCHAR(10) NULL DEFAULT NULL,
	`ename` VARCHAR(20) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`telephone` VARCHAR(50) NULL DEFAULT NULL,
	`address` VARCHAR(100) NULL DEFAULT NULL,
	`memo` VARCHAR(50) NULL DEFAULT NULL,
	`last_logout` TIMESTAMP NULL DEFAULT NULL
)


CREATE TABLE `board_tbl` (
	`seq` INT(100) NOT NULL,
	`name` VARCHAR(20) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`homepage` VARCHAR(50) NULL DEFAULT NULL,
	`title` VARCHAR(50) NULL DEFAULT NULL,
	`content` VARCHAR(4000) NULL DEFAULT NULL,
	`password` VARCHAR(20) NULL DEFAULT NULL,
	`count` INT(11) NULL DEFAULT NULL,
	`ip` VARCHAR(50) NULL DEFAULT NULL,
	`regdate` DATE NULL DEFAULT NULL,
	`pos` INT(11) NULL DEFAULT NULL,
	`depth` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`seq`)
)


COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
